global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  - job_name: 'test_metrics'
    static_configs:
      - targets: ['metrics_exporter:9090']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
